version: "3.9"
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=football
      - POSTGRES_USER=football
      - POSTGRES_PASSWORD=football
    container_name: football_api_db
  football:
    image: carlosvalarezo/football-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main
      - FLASK_ENV=desvelopment
      - PORT=5000
      - DB_NAME=football
      - DB_USER=football
      - DB_PASSWORD=football
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
    restart: on-failure:10
    volumes:
      - $PWD/api:/api
    container_name: football_api