version: "3.9"
services:
  football_db:
    image: postgres:10.21-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./api/db/db_script/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=football
      - POSTGRES_USER=football
      - POSTGRES_PASSWORD=football
    container_name: football_db
  football_api:
    build: .
    image: carlosvalarezo/football-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/api
      - PORT=5000
      - DB_NAME=football
      - DB_USER=football
      - DB_PASSWORD=football
      - DB_HOST=football_db
      - DB_PORT=5432
      - API_KEY_FOOTBALL=$API_KEY_FOOTBALL
      - FOOTBALL_URI=$FOOTBALL_URI
      - COMPETITIONS_ENDPOINT=$COMPETITIONS_ENDPOINT
    depends_on:
      - football_db
    restart: on-failure:10
    volumes:
      - $PWD/api:/api
    container_name: football_api