name: Football API actions
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Builds container image to run the tests
        run: docker build . -t carlosvalarezo/football_api_tests -f Dockerfile._dev
      - name: Execute the tests
        run: docker run -v "$PWD"/api/:/api carlosvalarezo/football_api_tests python -m pytest /api/tests
  deploy-to-heroku:
    needs: execute-tests
    runs-on: ubuntu-20.04
    environment: development
    container:
      image: heroku/heroku:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    # These manual commands of installing heroku & git CLIs should be replaced with provisioning tools like chef/ansible
      - name: Install heroku cli
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
#      - name: Install git cli
#        run: sudo apt install git-all
      - name: Checking CLIs version
        run: |
          heroku --version
          git --version
      - name: Create netrc file
        env:
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}"@users.noreply.github.com
          git config --global user.name "${GITHUB_ACTOR}"
          cat << EOF > ~/.netrc
          machine api.heroku.com
            login "$HEROKU_USERNAME"
            password "$HEROKU_API_KEY"
          EOF
          ls -all
          heroku apps:create football-api-two
          git push heroku master
#      - name: Login to heroku
#        run: heroku login
#      - name: Create heroku app
#        run: heroku create
