name: Football API actions
on: [push]
jobs:
  execute-tests:

    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Builds container image to run the tests
        run: docker build . -t carlosvalarezo/football_api_tests -f Dockerfile._dev
      - name: Execute the tests
        run: docker run -v "$PWD"/api/:/api carlosvalarezo/football_api_tests python -m pytest /api/tests
