#name: Football API actions
#on: [push]
#jobs:
#  execute-tests:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - name: Builds container image to run the tests
#        run: docker build . -t carlosvalarezo/football_api_tests -f Dockerfile._dev
#      - name: Execute the tests
#        run: docker run -v "$PWD"/api/:/api carlosvalarezo/football_api_tests python -m pytest /api/tests
#  deploy-to-heroku:
#    needs: execute-tests
#    runs-on: ubuntu-20.04
#    environment: development
#    container:
#      image: heroku/heroku:20
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#    # These manual commands of installing heroku CLI should be replaced with provisioning tools like chef/ansible
#      - name: Install heroku cli
#        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
#      - name: Checking CLIs version
#        run: |
#          heroku --version
#      - name: Create netrc file
#        env:
#          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#          GITHUB_EMAIL: ${{ github.event.pusher.email }}
#        run: |
#          echo "${GITHUB_ACTOR}"
#          echo "${GH_USERNAME}"
#          echo "${HOME}"
#          ls -all
#          git config --global user.email "${GITHUB_EMAIL}"
#          git config --global user.name "${GITHUB_ACTOR}"
#          git config --global --add safe.directory "*"
#          cat << EOF > "${HOME}"/.netrc
#          machine git.heroku.com
#          login "$HEROKU_USERNAME"
#          password "$HEROKU_API_KEY"
#          EOF
#          heroku git:remote -a cv-football-api
##          git remote add heroku git@git.heroku.com:project/cv-football-api.git
#          cat .git/config
#          git push heroku main

name: Football API actions
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Builds container image to run the tests
        run: docker build . -t carlosvalarezo/football_api_tests -f Dockerfile._dev
      - name: Execute the tests
        run: docker run -v "$PWD"/api/:/api carlosvalarezo/football_api_tests python -m pytest /api/tests
  deploy-to-heroku:
    needs: execute-tests
    runs-on: ubuntu-20.04
    environment: development
    container:
      image: heroku/heroku:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    # These manual commands of installing heroku CLI should be replaced with provisioning tools like chef/ansible
      - name: Install heroku cli
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Checking CLIs version
        run: |
          heroku --version
          git --version
      - name: Create netrc file
        env:
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          GITHUB_EMAIL: ${{ github.event.pusher.email }}
        run: |
          echo "${GITHUB_ACTOR}"
          echo "${GH_USERNAME}"
          ls -all
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global --add safe.directory "*"
          cat << EOF > "${HOME}"/.netrc
          machine git.heroku.com
            login $HEROKU_USERNAME
            password $HEROKU_API_KEY
          machine api.heroku.com
            login $HEROKU_USERNAME
            password $HEROKU_API_KEY
          EOF
          cat "${HOME}"/.netrc
          heroku git:remote -a cv-football-api
          cat .git/config
          git filter-branch -- --all
          git push heroku main
