name: Football API actions
on: [push]
jobs:
  show-messages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  execute-tests:
    runs-on: ubuntu-20.04
    steps:
      - run: docker build . -t carlosvalarezo/football_api_tests -f Dockerfile._dev
      - run: docker run -v "$PWD"/api/:/api carlosvalarezo/football_api_tests python -m pytest /api/tests
